#! /bin/sh

sxhkd &
urxvt -name scratchterm -e bash -c "fish -c 'tmux -f ~/.config/tmux/tmux.conf'" &

bspc monitor LVDS1 -d I II III IV V VI VII VIII
# bspc monitor HDMI2 -d VII VIII IX X

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

bspc config window_gap          0
bspc config border_width        3

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Firefox desktop='^1'
bspc rule -a Emacs desktop='^2' state=tiled
bspc rule -a MellowPlayer desktop='^10'
bspc rule -a URxvt:scratchterm monitor=LVDS-1 sticky=on state=floating locked=on hidden=on rectangle=500x300+418+27

# Set the border colors.
bspc config normal_border_color "$color0"
bspc config active_border_color "$color4"
bspc config focused_border_color "$color3"
bspc config presel_feedback_color "$color1"

systemctl --user import-environment DISPLAY
xsetroot -cursor_name left_ptr
if ! pgrep "polybar" > /dev/null 2>&1 ; then
    ~/.config/polybar/launch.sh &
fi


