#! /bin/sh

sxhkd &

bspc monitor DP1 -d I II III IV V VI VII VIII
bspc monitor HDMI2 -d IX X

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

bspc config window_gap          0
bspc config border_width        3

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Firefox desktop='^3'
bspc rule -a Emacs desktop='^4'
bspc rule -a MellowPlayer desktop='^8'

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

systemctl --user import-environment DISPLAY
xsetroot -cursor_name left_ptr
if ! pgrep "polybar" > /dev/null 2>&1 ; then
    ~/.config/polybar/launch.sh &
fi


